### ISSUE TITLE
Best way to clean up after?

### ISSUE THREAD

**Issue by timothystewart6** [gloveboxes/Windows-10-for-IoT-Graphics-Library-for-LED-Matrices#1]
Hi.  Thank you for this.  I am curious what the best way to clean up after it executes or end the current execution?

```
private void ScrollText() {
    var driver = new Ht16K33();
    LED8x8Matrix matrix = new LED8x8Matrix(driver);    
            while (true) {
                matrix.ScrollStringInFromRight("Hello World 2015 ", 100);
            }
}
```

```
Exception thrown: 'System.NullReferenceException' in Glovebox.Graphics.dll

```

If I call this method twice, I get a null reference exception when it tries to instantiate the driver again.

**Comment by gloveboxes** [comment]
hey there, from memory I implemented iDisposable so try

private void ScrollText() {
  var driver = new Ht16K33();
  using ( LED8x8Matrix matrix = new LED8x8Matrix(driver)) {
     while (true) {
                matrix.ScrollStringInFromRight("Hello World 2015 ", 100);
      }
  }
}

**Comment by gloveboxes** [comment]
you'll be getting the null exception because trying to open the I2C bus without having previously released it..
