### ISSUE TITLE
Clock

### ISSUE THREAD

**Issue by mezzo86** [gloveboxes/Windows-10-for-IoT-Graphics-Library-for-LED-Matrices#4]
Hello there,

First of all thank you for the glovebox library. I have a MAX7219 chain with 8 panels and I would like to simply show he current time. The only thing I was able to get to run so far is a scollingtext 'Hello World'.

Can you please give me a hint how I can show the current time without scrolling?

Thanks,
mezzo

**Comment by jrabarton** [comment]
you could draw the time like this.

```
char[] datetime = DateTime.Now.ToLocalTime().AddHours(1).ToString("HHmm").ToCharArray();
for (int i = 0; i < datetime.Length; i++)
    matrix.DrawString(datetime[i].ToString(), 0, i);
```

**Comment by mezzo86** [comment]
Thanks Jrabarton, this is working well and the LEDs are now displaying the time. I added "ss" to "HHmmss" to display the seconds. Can you help me to understand how I can get the clock 'ticking'? Should I use a timer or while loop?
